Feat/Avatar
joaooliveiradev/conduit-frontend pull request #15
Opened 2022-08-25 19:14 UTC by joaooliveiradev

2022-08-25 19:31 UTC, vmarcosp commented on src/components/Avatar/index.tsx
> +  const firstLetter = arrOfLetters.find((letter) =>
Essa regex tem um problema, ela considera somente chars sem acento. Se o nome for `Érica` a letra que ele vai pegar vai ser o R.

2022-08-25 19:32 UTC, vmarcosp commented on src/components/Avatar/index.tsx
> +  size: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
A ideia era usar número mesmo, eu acho que fica melhor porque fica mais flexivel. Dessa forma eu não consigo fazer algo tipo 1.5x o tamanho base ou 0.5x pra ficar menor que o tamanho base. Eu alteraria pra number mesmo, saca?

2022-08-25 19:32 UTC, vmarcosp commented on src/components/Avatar/Avatar.stories.tsx
> +        type: 'inline-radio',
Considerando que você vai alterar pra "number" o tipo do size, eu alteraria isso aqui pra um slider/range do storybook.

2022-08-25 19:33 UTC, vmarcosp requested changes
Tem algumas observações aí parsa

2022-08-25 20:17 UTC, joaooliveiradev commented
> Tem algumas observações aí parsa

Fix in this commit [4a5ba4](https://github.com/joaooliveiradev/conduit-frontend/commit/4a5ba4c8f5342fbe924dedaacbd854b2215f25f6)

2022-08-26 14:34 UTC, vmarcosp approved these changes
LGTM 🚀

2022-08-26 15:30 UTC, merged